---
# Copyright Red Hat
# SPDX-License-Identifier: Apache-2.0
#
# This playbook configures the Ceph repository.
# It also installs some prerequisites (podman, lvm2, chronyd, cephadm, ...)
#
# Usage:
#
# ansible-playbook -i <inventory host file> cephadm-preflight.yml
#
# You can limit the execution to a set of hosts by using `--limit` option:
#
# ansible-playbook -i <inventory host file> cephadm-preflight.yml --limit <my_osd_group|my_node_name>
#
# You can override variables using `--extra-vars` parameter:
#
# ansible-playbook -i <inventory host file> cephadm-preflight.yml --extra-vars "ceph_default_ceph_origin=rhcs"
#

- name: Variables validations
  ansible.builtin.import_playbook: validate/preflight.yml

- hosts: all
  become: true
  gather_facts: true
  vars:
    repos_to_disable: "{{ range(5, ceph_defaults_ceph_rhcs_version) | map('string') | map('regex_replace', '^', 'rhceph_') | map('regex_replace', '$', '-tools-for-rhel-' + ansible_facts['distribution_major_version'] + '-' + ansible_facts['architecture'] + '-rpms') | list }}"
    packages_to_uninstall:
      - ceph-mds
      - ceph-mgr
      - ceph-mon
      - ceph-osd
      - ceph-radosgw
      - rbd-mirror
  tasks:
    - name: Import_role ceph_defaults
      ansible.builtin.import_role:
        name: ceph_defaults

    - name: Redhat family of OS related tasks
      when: ansible_facts['os_family'] == 'RedHat'
      block:
        - name: Rhcs related tasks
          when: ceph_default_ceph_origin == 'rhcs'
          block:
            - name: Enable red hat ceph storage tools repository
              community.general.rhsm_repository:
                name: "rhceph-{{ ceph_defaults_ceph_rhcs_version }}-tools-for-rhel-{{ ansible_facts['distribution_major_version'] }}-{{ ansible_facts['architecture'] }}-rpms"

            - name: disable older rhceph repositories if any on RHEL{{ansible_facts['distribution_major_version']}}
              when: ansible_facts['distribution_major_version'] <= '8'
              rhsm_repository:
                name: "{{ repos_to_disable }}"
                state: absent

        - name: Enable ceph package repositories
          when: ceph_defaults_ceph_origin in ['community', 'ibm']
          block:
            - name: Set_fact _ceph_repo
              ansible.builtin.set_fact:
                _ceph_repo:
                  name: ceph_stable
                  description: "{{ 'Ceph Stable repo' if ceph_defaults_ceph_origin == 'community' else 'IBM Ceph repo' }}"
                  rpm_key: "{{ ceph_defaults_ceph_stable_key if ceph_defaults_ceph_origin == 'community' else ceph_defaults_ceph_ibm_key }}"
                  baseurl: "{{ ceph_defaults_ceph_community_repo_baseurll if ceph_defaults_ceph_origin == 'community' else ceph_defaults_ceph_ibm_repo_baseurl }}"
                  paths: "{{ [ 'noarch', '$basearch' ] if ceph_defaults_ceph_origin == 'community' else [ '$basearch' ] }}"

            - name: Configure ceph repository key
              ansible.builtin.rpm_key:
                key: "{{ _ceph_repo.rpm_key }}"
                state: present
              register: result
              until: result is succeeded

            - name: Configure ceph stable repository
              ansible.builtin.yum_repository:
                name: "ceph_stable_{{ item }}"
                description: "{{ _ceph_repo.description }} - {{ item }}"
                gpgcheck: true
                state: present
                gpgkey: "{{ _ceph_repo.rpm_key }}"
                baseurl: "{{ _ceph_repo.baseurl }}/{{ item }}"
                file: "ceph_stable_{{ item }}"
                priority: '2'
              register: result
              until: result is succeeded
              loop: "{{ _ceph_repo.paths }}"

        - name: Enable repo from shaman - dev
          when: ceph_defaults_ceph_origin == 'shaman'
          block:
            - name: Fetch ceph development repository
              ansible.builtin.uri:
                url:
                  "https://shaman.ceph.com/api/repos/ceph/\
                  {{ ceph_defaults_ceph_dev_branch }}/\
                  {{ ceph_defaults_ceph_dev_sha1 }}/\
                  centos/{{ ansible_facts['distribution_major_version'] }}/\
                  repo?arch={{ ansible_facts['architecture'] }}"
                return_content: true
              register: ceph_dev_yum_repo

            - name: Configure ceph development repository
              ansible.builtin.copy:
                content: "{{ ceph_dev_yum_repo.content }}"
                dest: /etc/yum.repos.d/ceph-dev.repo
                owner: root
                group: root
                mode: '0644'
                backup: true

            - name: Remove ceph_stable repositories
              ansible.builtin.yum_repository:
                name: '{{ item }}'
                file: ceph_stable
                state: absent
              with_items:
                - ceph_stable
                - ceph_stable_noarch

        - name: Enable custom repo
          when: ceph_defaults_ceph_origin == 'custom'
          block:
            - name: Set_fact ceph_custom_repositories
              ansible.builtin.set_fact:
                ceph_custom_repositories:
                  - name: Ceph_custom
                    description: Ceph custom repo
                    gpgcheck: "{{ 'yes' if custom_repo_gpgkey is defined else 'no' }}"
                    state: "{{ custom_repo_state | default('present') }}"
                    gpgkey: "{{ custom_repo_gpgkey | default(omit) }}"
                    baseurl: "{{ custom_repo_url }}"
                    enabled: "{{ custom_repo_enabled | default(1) }}"
                    file: ceph_custom
                    priority: '2'
              when: ceph_custom_repositories is undefined

            - name: Setup custom repositories
              ansible.builtin.yum_repository:
                name: "{{ item.name }}"
                description: "{{ item.description }}"
                state: "{{ item.state | default(omit) }}"
                gpgcheck: "{{ item.gpgcheck | default(omit) }}"
                gpgkey: "{{ item.gpgkey | default(omit) }}"
                baseurl: "{{ item.baseurl }}"
                file: "{{ item.ceph_custom | default(omit) }}"
                priority: "{{ item.priority | default(omit) }}"
                enabled: "{{ item.enabled | default(omit) }}"
              register: result
              until: result is succeeded
              loop: "{{ ceph_custom_repositories }}"

        - name: Install epel-release
          when: ansible_facts['distribution'] != 'RedHat'
          block:
            - name: Enable required CentOS repository for epel
              ansible.builtin.command: dnf config-manager --set-enabled "{{ 'powertools' if ansible_facts['distribution_major_version'] == '8' else 'crb' }}"
              changed_when: false

            - name: install epel package
              package:
                name: epel-release
                state: present
              register: result
              until: result is succeeded

        - name: Remove remaining local services ceph packages
          ansible.builtin.dnf:
            name: "{{ packages_to_uninstall }}"
            state: absent
            autoremove: false

        - name: Install ceph-common on rhel
          ansible.builtin.package:
            name: ceph-common
            state: "{{ (ceph_defaults_upgrade_ceph_packages | bool) | ternary('latest', 'present') }}"
          register: result
          until: result is succeeded

        - name: Install prerequisites packages on servers
          ansible.builtin.package:
            name: "{{ ceph_defaults_ceph_pkgs + infra_pkgs }}"
            state: "{{ (ceph_defaults_upgrade_ceph_packages | bool) | ternary('latest', 'present') }}"
          register: result
          until: result is succeeded
          when: group_names != [ceph_defaults_client_group]

        - name: Install prerequisites packages on clients
          ansible.builtin.package:
            name: "{{ ceph_defaults_ceph_client_pkgs }}"
            state: "{{ (ceph_defaults_upgrade_ceph_packages | bool) | ternary('latest', 'present') }}"
          register: result
          until: result is succeeded
          when: ceph_defaults_client_group in group_names


        - name: Ensure chronyd is running
          ansible.builtin.service:
            name: chronyd
            state: started
            enabled: true

    - name: Ubuntu related tasks
      when: ansible_facts['distribution'] == 'Ubuntu'
      block:
        - name: Enable repo from download.ceph.com
          block:
            - name: Prevent ceph certificate error
              ansible.builtin.apt:
                name: ca-certificates
                state: latest
                update_cache: true
              register: result
              until: result is succeeded

            - name: Configure ceph community repository stable key
              ansible.builtin.apt_key:
                url: "{{ ceph_defaults_ceph_stable_key }}"
                state: present

            - name: Configure Ceph community repository
              when: ceph_defaults_ceph_origin == 'community'
              ansible.builtin.apt_repository:
                repo: "deb https://download.ceph.com/debian-{{ ceph_defaults_ceph_release }}/ {{ ansible_facts['distribution_release'] }} main"
                state: present
                filename: ceph
                update_cache: false

            - name: Configure Ceph testing repository
              when: ceph_defaults_ceph_origin == 'testing'
              ansible.builtin.apt_repository:
                repo: "deb https://download.ceph.com/debian-testing/ {{ ansible_facts['distribution_release'] }} main"
                state: present
                filename: ceph
                update_cache: false

            - name: Configure Ceph custom repositories
              when: ceph_defaults_ceph_origin == 'custom'
              ansible.builtin.apt_repository:
                repo: "deb {{ item.baseurl }}/ {{ ansible_facts['distribution_release'] }} {{ item.components }}"
                state: "{{ item.state | default(omit) }}"
                filename: ceph_custom
                update_cache: false
              loop: "{{ ceph_custom_repositories }}"

        - name: Install prerequisites packages
          ansible.builtin.apt:
            name: "{{ ['python3','chrony'] + ceph_defaults_ceph_pkgs }}"
            state: "{{ (ceph_defaults_upgrade_ceph_packages | bool) | ternary('latest', 'present') }}"
            update_cache: true
          register: result
          until: result is succeeded

        - name: Ensure chronyd is running
          ansible.builtin.service:
            name: chronyd
            state: started
            enabled: true

        - name: Install container engine
          block:
            - name: Install podman
              when: ansible_facts['distribution_version'] is version('20.10', '>=')
              ansible.builtin.apt:
                name: podman
                state: present
                update_cache: true
              register: result
              until: result is succeeded

            - name: Install docker
              when: ansible_facts['distribution_version'] is version('20.10', '<')
              block:
                - name: Uninstall old version packages
                  ansible.builtin.apt:
                    name: "{{ item }}"
                    state: absent
                  loop:
                    - docker
                    - docker-engine
                    - docker.io
                    - containerd
                    - runc

                - name: Configure docker repository key
                  ansible.builtin.apt_key:
                    url: "https://download.docker.com/linux/ubuntu/gpg"
                    state: present

                - name: Setup docker repository
                  ansible.builtin.apt_repository:
                    repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_facts['distribution_release'] }} stable"
                    state: present
                    filename: docker
                    update_cache: false

                - name: Install docker
                  ansible.builtin.apt:
                    name: "{{ item }}"
                    state: present
                    update_cache: true
                  register: result
                  until: result is succeeded
                  loop:
                    - docker-ce
                    - docker-ce-cli
                    - containerd.io

- name: Set insecure container registry in /etc/containers/registries.conf
  ansible.builtin.import_playbook: cephadm-set-container-insecure-registries.yml
  when: set_insecure_registries | default(false) | bool
